// tests/run-all.js - Main test runner
const { runSuite } = require('./test-utils');

async function main() {
  const suites = [
    { name: 'TC-04: Lib Modules', file: 'suites/tc04-lib-modules.js', priority: 'P0' },
    { name: 'TC-01: Hook System', file: 'suites/tc01-hooks.js', priority: 'P0' },
    { name: 'TC-02: Skill System', file: 'suites/tc02-skills.js', priority: 'P0' },
    { name: 'TC-07: Configuration', file: 'suites/tc07-config.js', priority: 'P1' },
    { name: 'TC-03: Agent System', file: 'suites/tc03-agents.js', priority: 'P1' },
    { name: 'TC-05: MCP Server', file: 'suites/tc05-mcp.js', priority: 'P1' },
    { name: 'TC-06: TOML Commands', file: 'suites/tc06-commands.js', priority: 'P1' },
    { name: 'TC-08: Context Engineering', file: 'suites/tc08-context.js', priority: 'P1' },
    { name: 'TC-09: PDCA E2E', file: 'suites/tc09-pdca-e2e.js', priority: 'P0' },
    { name: 'TC-10: Philosophy', file: 'suites/tc10-philosophy.js', priority: 'P2' },
  ];

  let passed = 0, failed = 0, skipped = 0;
  for (const suite of suites) {
    const result = await runSuite(suite);
    passed += result.passed;
    failed += result.failed;
    skipped += result.skipped;
  }

  console.log(`\n${'='.repeat(60)}`);
  console.log(`Total: ${passed + failed + skipped} | Pass: ${passed} | Fail: ${failed} | Skip: ${skipped}`);
  console.log(`Pass Rate: ${(((passed || 0) / ((passed + failed) || 1)) * 100).toFixed(1)}%`);
  
  // Generate completion report logic
  generatePDCACompletionReport(passed, failed, skipped);
  
  process.exit(failed > 0 ? 1 : 0);
}

function generatePDCACompletionReport(passed, failed, skipped) {
  const fs = require('fs');
  const path = require('path');
  const date = new Date().toISOString().split('T')[0];
  const reportPath = path.resolve(__dirname, '../docs/04-report/features/bkit-gemini-v151-test.report.md');
  
  fs.mkdirSync(path.dirname(reportPath), { recursive: true });

  const matchRate = (((passed || 0) / ((passed + failed) || 1)) * 100).toFixed(1);

  let report = `# bkit-gemini v1.5.1 Comprehensive Test Report

> **Feature**: bkit-gemini-v151-test
> **Status**: ${failed === 0 ? 'COMPLETED' : 'IN_PROGRESS'}
> **Match Rate**: ${matchRate}%
> **Date**: ${date}

## 1. Summary

| Category | Passed | Failed | Skipped | Status |
|----------|--------|--------|---------|--------|
| Total | ${passed} | ${failed} | ${skipped} | ${failed === 0 ? '✅' : '❌'} |

## 2. Test Execution Details

The test suite covered 10 categories including Hook System, Skill System, Lib Modules, and Philosophy Alignment.

---
*Generated by bkit PDCA Act Phase*
`;

  fs.writeFileSync(reportPath, report);
}

main();