// tests/run-all.js - Main test runner for bkit-gemini v1.5.6
const { runSuite } = require('./test-utils');

async function main() {
  const suites = [
    // P0 - Must pass before release
    { name: 'TC-04: Lib Modules', file: 'suites/tc04-lib-modules.js', priority: 'P0' },
    { name: 'TC-01: Hook System', file: 'suites/tc01-hooks.js', priority: 'P0' },
    { name: 'TC-02: Skill System', file: 'suites/tc02-skills.js', priority: 'P0' },
    { name: 'TC-09: PDCA E2E', file: 'suites/tc09-pdca-e2e.js', priority: 'P0' },
    { name: 'TC-13: Automation', file: 'suites/tc13-automation.js', priority: 'P0' },
    { name: 'TC-16: v0.30.0 Phase 1 Migration', file: 'suites/tc16-v030-phase1.js', priority: 'P0' },
    { name: 'TC-18: v0.31.0 Feature Flags & Tool Annotations', file: 'suites/tc18-v031-features.js', priority: 'P0' },
    { name: 'TC-19: v0.31.0 Level Policy & Hook Adapter', file: 'suites/tc19-v031-policy-hooks.js', priority: 'P0' },
    { name: 'TC-20: Coverage Gap Fix (lib/pdca, lib/intent, etc.)', file: 'suites/tc20-coverage-gaps.js', priority: 'P1' },
    // P1 - Short-term integration
    { name: 'TC-07: Configuration', file: 'suites/tc07-config.js', priority: 'P1' },
    { name: 'TC-03: Agent System', file: 'suites/tc03-agents.js', priority: 'P1' },
    { name: 'TC-05: MCP Server', file: 'suites/tc05-mcp.js', priority: 'P1' },
    { name: 'TC-06: TOML Commands', file: 'suites/tc06-commands.js', priority: 'P1' },
    { name: 'TC-08: Context Engineering', file: 'suites/tc08-context.js', priority: 'P1' },
    { name: 'TC-11: Output Styles', file: 'suites/tc11-output-styles.js', priority: 'P1' },
    { name: 'TC-12: Agent Memory', file: 'suites/tc12-agent-memory.js', priority: 'P1' },
    { name: 'TC-17: v0.30.0 Phase 2 Integration', file: 'suites/tc17-v030-phase2.js', priority: 'P1' },
    // P2 - Medium-term refactoring
    { name: 'TC-14: bkend.ai Skills', file: 'suites/tc14-bkend-skills.js', priority: 'P2' },
    { name: 'TC-15: Feature Report', file: 'suites/tc15-feature-report.js', priority: 'P2' },
    { name: 'TC-10: Philosophy', file: 'suites/tc10-philosophy.js', priority: 'P2' },
  ];

  let passed = 0, failed = 0, skipped = 0;
  for (const suite of suites) {
    const result = await runSuite(suite);
    passed += result.passed;
    failed += result.failed;
    skipped += result.skipped;
  }

  console.log(`\n${'='.repeat(60)}`);
  console.log(`Total: ${passed + failed + skipped} | Pass: ${passed} | Fail: ${failed} | Skip: ${skipped}`);
  console.log(`Pass Rate: ${(((passed || 0) / ((passed + failed + skipped) || 1)) * 100).toFixed(1)}%`);
  
  // Generate completion report logic
  generatePDCACompletionReport(passed, failed, skipped);
  
  process.exit(failed > 0 ? 1 : 0);
}

function generatePDCACompletionReport(passed, failed, skipped) {
  const fs = require('fs');
  const path = require('path');
  const date = new Date().toISOString().split('T')[0];
  const reportPath = path.resolve(__dirname, '../docs/04-report/features/bkit-v156-gemini-test.report.md');

  fs.mkdirSync(path.dirname(reportPath), { recursive: true });

  const matchRate = (((passed || 0) / ((passed + failed + skipped) || 1)) * 100).toFixed(1);

  let report = `# bkit-gemini v1.5.6 Comprehensive Test Report

> **Feature**: bkit-v156-gemini-test
> **Status**: ${failed === 0 ? 'COMPLETED' : 'IN_PROGRESS'}
> **Match Rate**: ${matchRate}%
> **Date**: ${date}

## 1. Summary

| Category | Passed | Failed | Skipped | Status |
|----------|--------|--------|---------|--------|
| Total | ${passed} | ${failed} | ${skipped} | ${failed === 0 ? '✅' : '❌'} |

## 2. Test Execution Details

The test suite covered 19 categories including Hook System, Skill System, Lib Modules, MCP, TOML Commands, v1.5.6 Phase 1 Migration, and v1.5.6 Phase 2 Integration.
New v1.5.6 test suites (TC-18, TC-19) were successfully integrated and executed.
A total of ${passed + failed + skipped} automated test cases were executed.

---
*Generated by bkit PDCA Act Phase*
`;

  fs.writeFileSync(reportPath, report);
}

main();

